/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventConferenceDataConferenceSolutionKey } from './eventConferenceDataConferenceSolutionKey';
import { EventConferenceDataCreateRequestStatus } from './eventConferenceDataCreateRequestStatus';
import { ClassInfo } from './classInfo';


export interface EventConferenceDataCreateRequest { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    conferenceSolutionKey?: EventConferenceDataConferenceSolutionKey;
    requestId?: any | null;
    status?: EventConferenceDataCreateRequestStatus;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

