/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassInfo } from './classInfo';


export interface EventEnd { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    date?: string;
    dateTime?: string;
    timeZone?: any | null;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

