/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldInfoTersMethodForFieldInnerParametersInnerDeclaringExecutableTypeParametersInner } from './fieldInfoTersMethodForFieldInnerParametersInnerDeclaringExecutableTypeParametersInner';
import { FieldInfoFieldGenericType } from './fieldInfoFieldGenericType';
import { FieldInfoFieldAnnotatedType } from './fieldInfoFieldAnnotatedType';


export interface FieldInfoTersMethodForFieldInnerParametersInnerDeclaringExecutable { 
    name?: string;
    modifiers?: number;
    typeParameters?: Array<FieldInfoTersMethodForFieldInnerParametersInnerDeclaringExecutableTypeParametersInner>;
    synthetic?: boolean;
    declaredAnnotations?: any | null;
    varArgs?: boolean;
    annotatedParameterTypes?: Array<FieldInfoFieldAnnotatedType>;
    parameterCount?: number;
    parameterAnnotations?: any | null;
    genericParameterTypes?: Array<FieldInfoFieldGenericType>;
    genericExceptionTypes?: Array<FieldInfoFieldGenericType>;
    annotatedReturnType?: FieldInfoFieldAnnotatedType;
    annotatedReceiverType?: FieldInfoFieldAnnotatedType;
    annotatedExceptionTypes?: Array<FieldInfoFieldAnnotatedType>;
    annotations?: any | null;
    accessible?: boolean;
}

