/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldInfoFieldGenericType } from './fieldInfoFieldGenericType';
import { FieldInfoFieldAnnotatedType } from './fieldInfoFieldAnnotatedType';


export interface FieldInfoField { 
    name?: string;
    modifiers?: number;
    synthetic?: boolean;
    declaredAnnotations?: Array<any>;
    accessible?: boolean;
    genericType?: FieldInfoFieldGenericType;
    enumConstant?: boolean;
    annotatedType?: FieldInfoFieldAnnotatedType;
    annotations?: any | null;
}

