/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItem } from './orderItem';


export interface Order { 
    id?: number;
    invoiceNumber?: string;
    customerEmail?: string;
    customerName?: string;
    billingAddress?: string;
    billingCity?: string;
    billingPostalCode?: string;
    billingCountry?: string;
    totalAmount?: number;
    createdAt?: string;
    items?: Array<OrderItem>;
    sendCloudParcelId?: string;
    trackingNumber?: string;
    trackingUrl?: string;
    shippingStatus?: string;
    shippingLabelUrl?: string;
}

