/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Représentation complète d\'une commande pour le frontend
 */
export interface OrderDTO { 
    /**
     * ID unique de la commande
     */
    id: number;
    /**
     * Numéro de facture unique
     */
    invoiceNumber: string;
    /**
     * Email du client lors de la commande
     */
    customerEmail: string;
    /**
     * Nom complet du client
     */
    customerName: string;
    /**
     * Adresse de facturation
     */
    billingAddress: string;
    /**
     * Ville de facturation
     */
    billingCity: string;
    /**
     * Code postal de facturation
     */
    billingPostalCode: string;
    /**
     * Pays de facturation
     */
    billingCountry: string;
    /**
     * Montant total TTC
     */
    totalAmount: number;
    /**
     * Date et heure de création de la commande
     */
    createdAt: string;
    items: Array<any>;
    /**
     * ID du colis SendCloud
     */
    sendCloudParcelId?: string;
    /**
     * Numéro de suivi du transporteur
     */
    trackingNumber?: string;
    /**
     * Lien direct vers la page de suivi
     */
    trackingUrl?: string;
    /**
     * Statut de livraison
     */
    shippingStatus?: OrderDTO.ShippingStatusEnum;
    /**
     * URL vers l\'étiquette de transport PDF
     */
    shippingLabelUrl?: string;
}
export namespace OrderDTO {
    export type ShippingStatusEnum = 'Created' | 'Announced' | 'Shipped' | 'Delivered';
    export const ShippingStatusEnum = {
        Created: 'Created' as ShippingStatusEnum,
        Announced: 'Announced' as ShippingStatusEnum,
        Shipped: 'Shipped' as ShippingStatusEnum,
        Delivered: 'Delivered' as ShippingStatusEnum
    };
}


