export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './bookingController.service';
import { BookingControllerService } from './bookingController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './mediaController.service';
import { MediaControllerService } from './mediaController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './paymentController.service';
import { PaymentControllerService } from './paymentController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './productSizeController.service';
import { ProductSizeControllerService } from './productSizeController.service';
export * from './statsController.service';
import { StatsControllerService } from './statsController.service';
export * from './stoneController.service';
import { StoneControllerService } from './stoneController.service';
export * from './stripeWebhookController.service';
import { StripeWebhookControllerService } from './stripeWebhookController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, BookingControllerService, DashboardControllerService, MediaControllerService, OrderControllerService, PaymentControllerService, ProductControllerService, ProductSizeControllerService, StatsControllerService, StoneControllerService, StripeWebhookControllerService, UserControllerService];
