/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesDataPoint } from './salesDataPoint';


export interface DashboardStats { 
    totalRevenue?: number;
    totalOrders?: number;
    totalAppointments?: number;
    newCustomers?: number;
    /**
     * Données pour le graphique des ventes
     */
    salesChart?: Array<SalesDataPoint>;
}

