/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventConferenceDataConferenceSolution } from './eventConferenceDataConferenceSolution';
import { EventConferenceDataParameters } from './eventConferenceDataParameters';
import { EventConferenceDataCreateRequest } from './eventConferenceDataCreateRequest';
import { ClassInfo } from './classInfo';


export interface EventConferenceData { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    conferenceId?: any | null;
    conferenceSolution?: EventConferenceDataConferenceSolution;
    createRequest?: EventConferenceDataCreateRequest;
    entryPoints?: any | null;
    notes?: any | null;
    parameters?: EventConferenceDataParameters;
    signature?: any | null;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

