/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassInfo } from './classInfo';


export interface EventGadget { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    display?: any | null;
    height?: any | null;
    iconLink?: any | null;
    link?: any | null;
    preferences?: { [key: string]: any; };
    title?: any | null;
    type?: any | null;
    width?: any | null;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

