/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventSource } from './eventSource';
import { EventReminders } from './eventReminders';
import { EventGadget } from './eventGadget';
import { EventEnd } from './eventEnd';
import { EventExtendedProperties } from './eventExtendedProperties';
import { EventCreator } from './eventCreator';
import { ClassInfo } from './classInfo';
import { EventConferenceData } from './eventConferenceData';


export interface Event { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    anyoneCanAddSelf?: any | null;
    attachments?: any | null;
    attendees?: any | null;
    attendeesOmitted?: any | null;
    colorId?: any | null;
    conferenceData?: EventConferenceData;
    created?: string;
    creator?: EventCreator;
    description?: any | null;
    end?: EventEnd;
    endTimeUnspecified?: any | null;
    etag?: any | null;
    eventType?: any | null;
    extendedProperties?: EventExtendedProperties;
    gadget?: EventGadget;
    guestsCanInviteOthers?: any | null;
    guestsCanModify?: any | null;
    guestsCanSeeOtherGuests?: any | null;
    hangoutLink?: any | null;
    htmlLink?: any | null;
    id?: any | null;
    kind?: any | null;
    location?: any | null;
    locked?: any | null;
    organizer?: EventCreator;
    originalStartTime?: EventEnd;
    privateCopy?: any | null;
    recurrence?: any | null;
    recurringEventId?: any | null;
    reminders?: EventReminders;
    sequence?: any | null;
    source?: EventSource;
    start?: EventEnd;
    status?: any | null;
    summary?: any | null;
    transparency?: any | null;
    updated?: string;
    visibility?: any | null;
    icalUID?: any | null;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

