/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventConferenceDataParametersAddOnParameters } from './eventConferenceDataParametersAddOnParameters';
import { ClassInfo } from './classInfo';


export interface EventConferenceDataParameters { 
  [key: string]: any | any;


    classInfo?: ClassInfo;
    addOnParameters?: EventConferenceDataParametersAddOnParameters;
    factory?: any | null;
    unknownKeys?: { [key: string]: any; };
    empty?: any | null;
}

