/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldInfoFieldGenericType } from './fieldInfoFieldGenericType';
import { FieldInfoTersMethodForFieldInnerParametersInner } from './fieldInfoTersMethodForFieldInnerParametersInner';
import { FieldInfoTersMethodForFieldInnerTypeParametersInner } from './fieldInfoTersMethodForFieldInnerTypeParametersInner';
import { FieldInfoFieldAnnotatedType } from './fieldInfoFieldAnnotatedType';


export interface FieldInfoTersMethodForFieldInner { 
    name?: string;
    modifiers?: number;
    typeParameters?: Array<FieldInfoTersMethodForFieldInnerTypeParametersInner>;
    synthetic?: boolean;
    declaredAnnotations?: any | null;
    accessible?: boolean;
    varArgs?: boolean;
    parameterCount?: number;
    parameterAnnotations?: Array<any>;
    genericParameterTypes?: Array<FieldInfoFieldGenericType>;
    genericExceptionTypes?: Array<FieldInfoFieldGenericType>;
    _default?: boolean;
    genericReturnType?: FieldInfoFieldGenericType;
    bridge?: boolean;
    defaultValue?: any | null;
    annotatedReturnType?: FieldInfoFieldAnnotatedType;
    annotatedParameterTypes?: Array<FieldInfoFieldAnnotatedType>;
    parameters?: Array<FieldInfoTersMethodForFieldInnerParametersInner>;
    annotatedReceiverType?: FieldInfoFieldAnnotatedType;
    annotatedExceptionTypes?: Array<FieldInfoFieldAnnotatedType>;
    annotations?: any | null;
}

