/**
 * Univers des Âmes API
 * API REST pour la boutique et les services de l\'Univers des Âmes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldInfoFieldGenericType } from './fieldInfoFieldGenericType';
import { FieldInfoField } from './fieldInfoField';
import { FieldInfoTersMethodForFieldInner } from './fieldInfoTersMethodForFieldInner';


export interface FieldInfo { 
    field?: FieldInfoField;
    name?: string;
    primitive?: boolean;
    _final?: boolean;
    genericType?: FieldInfoFieldGenericType;
    classInfo?: any | null;
    tersMethodForField?: Array<FieldInfoTersMethodForFieldInner>;
}

